/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "primary-fixed": "#ffe16d",
        "tertiary-container": "#cbdaff",
        "outline-variant": "#d0c6ab",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#ffd700",
        "surface-dim": "#e1d9c7",
        "surface-container": "#f6edda",
        "secondary-fixed-dim": "#c0c6db",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004395",
        "error-container": "#ffdad6",
        "secondary": "#575e70",
        "background": "#fff9ef",
        "tertiary-fixed-dim": "#adc6ff",
        "inverse-surface": "#343024",
        "inverse-on-surface": "#f9f0dd",
        "inverse-primary": "#e9c400",
        "on-primary-fixed-variant": "#544600",
        "surface-variant": "#eae2cf",
        "surface": "#fff9ef",
        "secondary-container": "#d9dff5",
        "on-background": "#1f1b10",
        "secondary-fixed": "#dce2f7",
        "surface-tint": "#705d00",
        "primary-fixed-dim": "#e9c400",
        "on-secondary-fixed": "#141b2b",
        "on-tertiary-fixed": "#001a42",
        "tertiary": "#005ac2",
        "on-secondary-fixed-variant": "#404758",
        "error": "#ba1a1a",
        "on-tertiary-container": "#005bc4",
        "on-secondary-container": "#5c6274",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#fff9ef",
        "surface-container-high": "#f0e7d5",
        "on-surface": "#1f1b10",
        "primary": "#705d00",
        "surface-container-low": "#fbf3e0",
        "tertiary-fixed": "#d8e2ff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#221b00",
        "outline": "#7e775f",
        "on-primary-container": "#705e00",
        "on-surface-variant": "#4d4732",
        "surface-container-highest": "#eae2cf"
      },
      "fontFamily": {
        "plus-jakarta": ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
}
